# Generated by Django 4.1 on 2022-08-17 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.BigAutoField(default='100', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('contact', models.CharField(default='000', max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('m_id', models.BigAutoField(default='00', primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('d_id', models.BigAutoField(default='1000', primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'unsent'), (1, 'sent')], default=0)),
                ('email_pk', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='promomail.customer')),
                ('message_pk', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='promomail.message')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
    ]
