# Generated by Django 4.1 on 2022-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promomail', '0002_alter_message_m_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
