# Generated by Django 4.1 on 2022-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promomail', '0003_alter_customer_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='d_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
