# Generated by Django 4.1 on 2022-08-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promomail', '0004_alter_delivery_d_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
        ),
    ]
